services:
  - type: web
    name: survey-app-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
databases:
  - name: survey-app-db
    databaseName: survey_management
    user: survey_user
    plan: free